### ISSUE TITLE
Open appindicator Using Right-Click, doesn't perform any action!

### ISSUE THREAD

**Issue by Syntist** [UbuntuBudgie/budgie-indicator-applet#12]
When i right click the appindicator, and select something from menu it dosen't do anything unless i open the menu using left click.

**Comment by fossfreedom** [comment]
hmm.  confirmed. thanks.

PRs to resolve are welcome.

**Comment by Syntist** [comment]
Any fix for this yet?

**Comment by fossfreedom** [comment]
@Syntist "PRs to resolve are welcome."

**Comment by nickdonnelly** [comment]
Also tray icons that allow single left-clicks to perform actions simply don't work at all. It just displays the context menu as if you right clicked.

**Comment by fossfreedom** [comment]
@nickdonnelly example?

**Comment by nickdonnelly** [comment]
@fossfreedom For example, Telegram. Left clicking the icon should show or hide the telegram window but instead it opens the context menu.

**Comment by fossfreedom** [comment]
@nickdonnelly I don't see anything here (I may be missing something obvious) that deals with left vs  right clicks https://github.com/UbuntuBudgie/budgie-indicator-applet/blob/master/src/applet-main.c

Wondering what happens with other desktop environments that use an appindicator applet e.g. Ubuntu Mate?

Trying to pin-down if this is how apps that have coded specifically with appindicators behave compared to those environments that use the obsolete X11 system tray (I say obsolete because in the Wayland world the system tray concept doesnt exist as currently implemented).

**Comment by nickdonnelly** [comment]
@fossfreedom I've not tried it in other environments that use appindicator (at least that I'm aware of). On Solus, which uses budgie, everything worked as intended, but I'm not sure that my particular version of Solus was using appindicator (and I can't check, that drive failed on me!).

**Comment by pclark36** [comment]
So I've figured out that if you right click the menu, you have to right click the menu for the action to take place.  If you left click to bring up the context menu, you need to left click for the menu action.  If you right click, and then left click, nothing happens, if you left click then right click.  Nothign happens.

**Comment by fossfreedom** [comment]
ok - like Mate I have now disabled right-click events - so you can only open the appindicator via left click ... which is the same standard as normal budgie-applets.

**Comment by fossfreedom** [comment]
oops - reopen - only close once fix uploaded to 19.10 repos.
