### ISSUE TITLE
How to get Budgie show certain indicator icons?

### ISSUE THREAD

**Issue by swarnendubiswas** [UbuntuBudgie/budgie-indicator-applet#8]
Hi,

I have Ubuntu Gnome 17.04, and have installed Budgie 10.3.1 from `ppa:ubuntubudgie/backports`. I have got a few app indicators to work, namely Dropbox, Telegram, Variety. However, a few indicators don't show up. For example, the power/battery setting, the network indicator, Skype. Is there any package that needs to be installed for this? Or is there any trick/limitation in getting this to work? Thanks.

**Comment by fossfreedom** [comment]
power is supplied by a native budgie applet. make sure you have not accidentally removed the status applet.

Network is supplied by the system tray applet. Check in your process list. nm-applet must be started with --no-indicator as a parameter otherwise it will not appear. If you see nm-applet by itself then that's a conflict coming from gnome that you will need to resolve.

Skype I have never tried but since it's just an app it should work.


On 22 May 2017 03:29, Swarnendu Biswas <notifications@github.com> wrote:

Hi,

I have Ubuntu Gnome 17.04, and have installed Budgie 10.3.1 from ppa:ubuntubudgie/backports. I have got a few app indicators to work, namely Dropbox, Telegram, Variety. However, a few indicators don't show up. For example, the power/battery setting, the network indicator, Skype. Is there any package that needs to be installed for this? Or is there any trick/limitation in getting this to work? Thanks.

**Comment by swarnendubiswas** [comment]
Thanks for your suggestions. I have added status applet, I was confused by the name as to what was its purpose. It adds battery and sound indicators.

`nm-applet` is running but with no parameters. Are you aware of a way by which I can fix it without affecting Gnome?

I have app indicator applet added and have removed system tray applet. But the indicator for Skye v5.2 does not appear.

**Comment by fossfreedom** [comment]
You have to run the system tray applet for nm-applet to appear. nm-applet --no-indicator must then be run.

Suggest script a startup application. It would use a "only in=budgie" type statement to only run for budgie. See the budgie startup file in /etc/xdg/autostart.

This script would 

killall nm-applet
sleep 5
nm-applet --no-indicator

Otherwise you are into recompiling budgie-indicator-applet but reenabling the code that deliberately hides the network indicator.

No idea on Skype. It's not something I run. If I find sometime I will try to investigate.

**Comment by swarnendubiswas** [comment]
Thanks, adding the system-tray applet and running `nm-applet --no-indicator` resolves the issue with network indicator. I had removed the system-tray applet since [certain articles](http://www.omgubuntu.co.uk/2016/11/budgie-desktop-picks-indicator-applet-support) suggested that the appindicator applet and the system-tray applet do not run side-by-side. 

I will work on adding a startup script.

**Comment by swarnendubiswas** [comment]
Enabling system-tray allows to show Skype as well. Thanks for helping.
